# .circleci/config.yml
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.4.1
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: Run Test
          command: npm test
  deploy-to-staging:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku Staging
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_STAGING.git master
  e2e-test:
    docker:
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: npm ci
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: # cleanup test db
          name: Cleanup before Test
          command: npm run test:cypress:cleanup
      - run: # run tests
          name: Run Cypress Test (headless)
          command: npm run test:cypress-headless
      - run: # cleanup test db
          name: Cleanup after Test
          command: npm run test:cypress:cleanup
      - run:
          command: |
            mkdir -p /tmp/video_dumps
            cp /root/project/cypress/videos.* /tmp/video_dumps
          when: on_fail
      - store_artifacts:
          path: /tmp/video_dumps
  deploy-to-production:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku Prod
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_PRODUCTION.git master
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-to-staging:
          filters:
            branches:
              only: master
          requires:
            - build
      - e2e-test:
          filters:
            branches:
              only: master
          requires:
            - deploy-to-staging
      - hold:
          type: approval
          requires:
            - e2e-test
      - deploy-to-production:
          filters:
            branches:
              only: master
          requires:
            - hold